version: "3.8"
services:
  db:
    image: postgres:15.4-alpine
    restart: always
    env_file: ./.env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME    
    networks:
      - my-network
    volumes: 
      - postgres_storage:/var/lib/postgresql/data
      
  app:
    build: ./
    ports:
      - 5000:5000
    env_file: ./.env
    environment:
      DB_HOST: db
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
    networks:
      - my-network
    depends_on:
      - db 

networks:
  my-network:
    name: my-network
    
volumes:
  postgres_storage: